package navspringboot.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.ArrayList;

/*
existing table:

        CREATE TABLE `data` (
        `DataID` int(11) NOT NULL AUTO_INCREMENT,
        `ModuleName` varchar(80) DEFAULT NULL,
        `ObjectType` varchar(80) DEFAULT NULL,
        `Description` varchar(80) DEFAULT NULL,
        `RangeFrom` int(20) DEFAULT NULL,
        `RangeTo` int(20) DEFAULT NULL,
        `Read` varchar(10) DEFAULT NULL,
        `Insert` varchar(10) DEFAULT NULL,
        `Modify` varchar(10) DEFAULT NULL,
        `Delete` varchar(10) DEFAULT NULL,
        `Execute` varchar(10) DEFAULT NULL,
        `ProductLine` varchar(80) DEFAULT NULL,
        `ModuleID` int(20) DEFAULT NULL,
        `VersionName` varchar(20) DEFAULT NULL,
        `ModuleID2` int(20) DEFAULT NULL,
        PRIMARY KEY (`DataID`)
        ) ENGINE=InnoDB AUTO_INCREMENT=649631 DEFAULT CHARSET=utf8;
*/


@Entity
@Table(name = "data")
public class Data {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each Data in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long dataid;
  private String modulename;
  private String objecttype;
  private String description;
  private Long rangefrom;
  private Long rangeto;
  private String read;
  private String insert;
  private String modify;
  private String delete;
  private String execute;
  private String productline;
  private Long moduleid;
  private String versionname;
  private Long moduleid2;


  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Data() { }

  public Data(long dataid) {
    this.dataid = dataid;
  }

  public Data(String modulename, String objecttype, String description, Long rangefrom, Long rangeto, String read, String insert, String modify, String delete, String execute, String productline, Long moduleid, String versionname, Long moduleid2) {
    this.modulename = modulename;
    this.objecttype = objecttype;
    this.description = description;
    this.rangefrom = rangefrom;
    this.rangeto = rangeto;
    this.read = read;
    this.insert = insert;
    this.modify = modify;
    this.delete = delete;
    this.execute = execute;
    this.productline = productline;
    this.moduleid = moduleid;
    this.versionname = versionname;
    this.moduleid2 = moduleid2;
  }

    public ArrayList<String> getTypes() {
        ArrayList<String> Types = new ArrayList<String>();

        Types.add("TableData");
        Types.add("TableDescription");
        Types.add("Form");
        Types.add("Report");
        Types.add("Dataport");
        Types.add("XMLport");
        Types.add("Codeunit");
        Types.add("MenuSuite");
        Types.add("Page");

        return Types;
    }

// Getter and setter methods

  public Long getDataid() {
    return dataid;
  }

  public void setDataid(Long dataid) {
    this.dataid = dataid;
  }

  public String getModulename() {
    return modulename;
  }

  public void setModulename(String modulename) {
    this.modulename = modulename;
  }

  public String getObjecttype() {
    return objecttype;
  }

  public void setObjecttype(String objecttype) {
    this.objecttype = objecttype;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Long getRangefrom() {
    return rangefrom;
  }

  public void setRangefrom(Long rangefrom) {
    this.rangefrom = rangefrom;
  }

  public Long getRangeto() {
    return rangeto;
  }

  public void setRangeto(Long rangeto) {
    this.rangeto = rangeto;
  }

  public String getRead() {
    return read;
  }

  public void setRead(String read) {
    this.read = read;
  }

  public String getInsert() {
    return insert;
  }

  public void setInsert(String insert) {
    this.insert = insert;
  }

  public String getModify() {
    return modify;
  }

  public void setModify(String modify) {
    this.modify = modify;
  }

  public String getDelete() {
    return delete;
  }

  public void setDelete(String delete) {
    this.delete = delete;
  }

  public String getExecute() {
    return execute;
  }

  public void setExecute(String execute) {
    this.execute = execute;
  }

  public String getProductline() {
    return productline;
  }

  public void setProductline(String productline) {
    this.productline = productline;
  }

  public Long getModuleid() {
    return moduleid;
  }

  public void setModuleid(Long moduleid) {
    this.moduleid = moduleid;
  }

  public String getVersionname() {
    return versionname;
  }

  public void setVersionname(String versionname) {
    this.versionname = versionname;
  }

  public Long getModuleid2() {
    return moduleid2;
  }

  public void setModuleid2(Long moduleid2) {
    this.moduleid2 = moduleid2;
  }
} // class Data
